# Generated by Django 5.2.1 on 2026-02-05 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMajitele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_premium', models.BooleanField(default=False)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('uzivatel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('vek', models.PositiveIntegerField()),
                ('popis', models.TextField(blank=True)),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='psi_fotky/')),
                ('cip', models.CharField(max_length=50, unique=True)),
                ('posledni_ockovani', models.DateField(blank=True, null=True)),
                ('posledni_odcerveni', models.DateField(blank=True, null=True)),
                ('majitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi', to='users.profilmajitele')),
            ],
        ),
    ]
