# Generated by Django 5.2.1 on 2026-02-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pes',
            name='posledni_ockovani',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='posledni_odcerveni',
        ),
    ]
