# Generated by Django 5.2.1 on 2026-02-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_pes_posledni_ockovani_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plemeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ikona', models.ImageField(blank=True, null=True, upload_to='plemena_ikony/')),
            ],
            options={
                'verbose_name_plural': 'Plemena',
            },
        ),
        migrations.AddField(
            model_name='pes',
            name='posledni_ockovani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pes',
            name='posledni_odcerveni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilmajitele',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profilmajitele',
            name='uzivatel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Prispevek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='social_fotky/')),
                ('video', models.FileField(blank=True, null=True, upload_to='social_videa/')),
                ('text', models.TextField()),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moje_prispevky', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='oblibene_prispevky', to=settings.AUTH_USER_MODEL)),
                ('plemeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prispevky_na_zed', to='users.plemeno')),
            ],
            options={
                'ordering': ['-datum_pridani'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prispevek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='users.prispevek')),
            ],
        ),
    ]
