# Generated by Django 5.2.1 on 2026-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plemeno_pes_posledni_ockovani_pes_posledni_odcerveni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plemeno',
            name='kategorie',
            field=models.CharField(choices=[('ostatni', 'Běžná plemena'), ('lovecka', 'Lovečtí psi'), ('vystavy', 'Výstavy a šampionáty')], default='ostatni', max_length=20),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
