# Generated by Django 5.2.1 on 2026-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_plemeno_kategorie_alter_plemeno_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plemeno',
            name='datum_konani',
            field=models.DateField(blank=True, null=True, verbose_name='Datum konání'),
        ),
        migrations.AddField(
            model_name='plemeno',
            name='misto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Místo konání'),
        ),
        migrations.AddField(
            model_name='plemeno',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='plemeno',
            name='poradatel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pořadatel'),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='kategorie',
            field=models.CharField(choices=[('ostatni', 'Běžná plemena'), ('lovecka', 'Lovečtí psi / Akce'), ('vystavy', 'Výstavy a šampionáty')], default='ostatni', max_length=20),
        ),
    ]
