# Generated by Django 5.2.1 on 2026-02-06 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_plemeno_datum_konani_plemeno_misto_plemeno_popis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentar',
            options={'ordering': ['datum_pridani']},
        ),
        migrations.AddField(
            model_name='komentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpovedi', to='users.komentar'),
        ),
    ]
