# Generated by Django 5.2.1 on 2026-02-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_komentar_options_komentar_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ockovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum očkování')),
                ('nazev_vakciny', models.CharField(max_length=100, verbose_name='Název vakcíny / Nemoc')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ockovani_zaznamy', to='users.pes')),
            ],
            options={
                'verbose_name': 'Očkování',
                'verbose_name_plural': 'Očkování',
                'ordering': ['-datum'],
            },
        ),
    ]
