# Generated by Django 5.2.1 on 2026-02-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ockovani'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ockovani',
            options={'ordering': ['-datum']},
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='nazev_vakciny',
            field=models.CharField(max_length=100, verbose_name='Název vakcíny'),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='pes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vsechna_ockovani', to='users.pes'),
        ),
    ]
