# Generated by Django 5.2.1 on 2026-02-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ockovani_options_alter_ockovani_nazev_vakciny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='posledni_klistata',
            field=models.DateField(blank=True, null=True, verbose_name='Poslední ošetření proti klíšťatům'),
        ),
    ]
