# Generated by Django 5.2.1 on 2026-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pes_posledni_klistata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='je_ztraceny',
            field=models.BooleanField(default=False, verbose_name='Hledá se'),
        ),
        migrations.AddField(
            model_name='pes',
            name='qr_kod',
            field=models.ImageField(blank=True, null=True, upload_to='qr_kody/'),
        ),
    ]
