# Generated by Django 5.2.1 on 2026-02-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pes_je_ztraceny_pes_qr_kod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ockovani',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prispevek',
            options={},
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='parent',
        ),
        migrations.AddField(
            model_name='pes',
            name='matka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potomci_matka', to='users.pes'),
        ),
        migrations.AddField(
            model_name='pes',
            name='matka_manualni',
            field=models.CharField(blank=True, help_text='Pokud matka není v systému', max_length=255),
        ),
        migrations.AddField(
            model_name='pes',
            name='otec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potomci_otec', to='users.pes'),
        ),
        migrations.AddField(
            model_name='pes',
            name='otec_manualni',
            field=models.CharField(blank=True, help_text='Pokud otec není v systému', max_length=255),
        ),
        migrations.AddField(
            model_name='pes',
            name='zdravotni_testy',
            field=models.TextField(blank=True, help_text='Např. DKK A/A, DLK 0/0'),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='nazev_vakciny',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='poznamka',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='kategorie',
            field=models.CharField(choices=[('ostatni', 'Běžná plemena'), ('lovecka', 'Lovečtí psi'), ('vystavy', 'Výstavy')], default='ostatni', max_length=20),
        ),
        migrations.CreateModel(
            name='GalerieFotka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='galerie_psu/')),
                ('popisek', models.CharField(blank=True, max_length=200)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_fotky', to='users.pes')),
            ],
        ),
        migrations.CreateModel(
            name='GalerieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Odkaz na YouTube/Vimeo')),
                ('popisek', models.CharField(blank=True, max_length=200)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_videa', to='users.pes')),
            ],
        ),
        migrations.CreateModel(
            name='Uspech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('výstava', 'Výstava'), ('zkouška', 'Zkouška'), ('sport', 'Sportovní úspěch'), ('titul', 'Titul'), ('jiné', 'Jiné')], default='výstava', max_length=50)),
                ('nazev', models.CharField(max_length=255)),
                ('popis', models.TextField(blank=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('misto', models.CharField(blank=True, max_length=255)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uspechy', to='users.pes')),
            ],
            options={
                'verbose_name_plural': 'Úspěchy',
                'ordering': ['-datum'],
            },
        ),
    ]
