# Generated by Django 5.2.1 on 2026-02-09 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_komentar_options_alter_ockovani_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerievideo',
            name='datum_pridani',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 9, 17, 11, 16, 240434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galerievideo',
            name='video_soubor',
            field=models.FileField(blank=True, null=True, upload_to='videa_psu/'),
        ),
        migrations.AddField(
            model_name='pes',
            name='barva',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pes',
            name='bonitace',
            field=models.TextField(blank=True, verbose_name='Bonitační kód / Chovnost'),
        ),
        migrations.AddField(
            model_name='pes',
            name='cislo_zapisu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Číslo zápisu'),
        ),
        migrations.AddField(
            model_name='pes',
            name='genetika_dna',
            field=models.TextField(blank=True, verbose_name='Genetické testy (např. PRA, CEA, DM)'),
        ),
        migrations.AddField(
            model_name='pes',
            name='rtg_ed',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dysplazie loketního kloubu (ED)'),
        ),
        migrations.AddField(
            model_name='pes',
            name='rtg_hd',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dysplazie kyčelního kloubu (HD)'),
        ),
        migrations.AddField(
            model_name='pes',
            name='rtg_pater',
            field=models.CharField(blank=True, max_length=50, verbose_name='Spondylóza / Páteř'),
        ),
        migrations.AddField(
            model_name='pes',
            name='srst',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='galerievideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Odkaz na YouTube nebo Vimeo', null=True),
        ),
    ]
