# Generated by Django 5.2.1 on 2026-02-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_galerievideo_datum_pridani_galerievideo_video_soubor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='narozeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='profilmajitele',
            name='premium_do',
            field=models.DateField(blank=True, null=True),
        ),
    ]
