# Generated by Django 5.2.1 on 2026-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pes_narozeni_profilmajitele_premium_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='plemeno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='plemena_foto/'),
        ),
        migrations.AddField(
            model_name='plemeno',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='plemena_video/'),
        ),
        migrations.AlterField(
            model_name='galeriefotka',
            name='popisek',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
