# Generated by Django 5.2.1 on 2026-02-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_plemeno_foto_plemeno_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZdravotniZaznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('urgentni', '🚨 Urgentní (bolest, úraz)'), ('zaznam', '📝 Běžný záznam (změna chování)'), ('kontrolni', '🏥 Kontrolní měření (váha, teplota)')], default='zaznam', max_length=20)),
                ('titulek', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaznamy', to='users.pes')),
            ],
        ),
    ]
