# Generated by Django 5.2.1 on 2026-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_zdravotnizaznam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plemeno',
            name='datum_konani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='misto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='poradatel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
