# Generated by Django 5.2.1 on 2026-02-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_plemeno_datum_konani_alter_plemeno_misto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plemeno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uspech',
            options={},
        ),
        migrations.RemoveField(
            model_name='galerievideo',
            name='datum_pridani',
        ),
        migrations.RemoveField(
            model_name='zdravotnizaznam',
            name='typ',
        ),
        migrations.AddField(
            model_name='pes',
            name='typ_ochrany_klistata',
            field=models.IntegerField(choices=[(30, 'Pipeta / Spot-on (1 měsíc)'), (90, 'Tableta (3 měsíce)'), (210, 'Obojek Foresto (7 měsíců)'), (240, 'Obojek Scalibor (8 měsíců)')], default=30, verbose_name='Typ ochrany'),
        ),
        migrations.AlterField(
            model_name='galerievideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='bonitace',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='cislo_zapisu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pes',
            name='genetika_dna',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='je_ztraceny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pes',
            name='matka_manualni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pes',
            name='otec_manualni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pes',
            name='posledni_klistata',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_ed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_hd',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_pater',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pes',
            name='zdravotni_testy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='kategorie',
            field=models.CharField(default='ostatni', max_length=20),
        ),
        migrations.AlterField(
            model_name='uspech',
            name='typ',
            field=models.CharField(default='výstava', max_length=50),
        ),
    ]
