# Generated by Django 5.2.1 on 2026-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_plemeno_options_alter_uspech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='posledni_pipeta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
