# Generated by Django 5.2.1 on 2026-02-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_pes_posledni_pipeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('like', 'Lajk'), ('komentar', 'Komentář'), ('odpoved', 'Odpověď')], max_length=20)),
                ('precteno', models.BooleanField(default=False)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('odesilatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odeslane_notifikace', to=settings.AUTH_USER_MODEL)),
                ('prijemce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijate_notifikace', to=settings.AUTH_USER_MODEL)),
                ('prispevek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.prispevek')),
            ],
            options={
                'ordering': ['-datum_vytvoreni'],
            },
        ),
    ]
