# Generated by Django 5.2.1 on 2026-02-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notifikace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikace',
            name='typ',
            field=models.CharField(choices=[('like', 'Lajk'), ('komentar', 'Komentář'), ('odpoved', 'Odpověď'), ('ockovani', 'Blížící se očkování'), ('odcerveni', '💊 Odčervení'), ('klistata', '💧 Klíšťata')], max_length=20),
        ),
    ]
