# Generated by Django 5.2.1 on 2026-02-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notifikace_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pes',
            name='matka',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='otec',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='posledni_pipeta',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='qr_kod',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='zdravotni_testy',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='datum_konani',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='ikona',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='kategorie',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='misto',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='poradatel',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='video',
        ),
        migrations.RemoveField(
            model_name='prispevek',
            name='video',
        ),
        migrations.RemoveField(
            model_name='profilmajitele',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='uspech',
            name='misto',
        ),
        migrations.AddField(
            model_name='komentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpovedi', to='users.komentar'),
        ),
        migrations.AlterField(
            model_name='notifikace',
            name='typ',
            field=models.CharField(choices=[('like', 'Lajk'), ('komentar', 'Komentář'), ('odpoved', 'Odpověď')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='nazev_vakciny',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pes',
            name='barva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='bonitace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='cip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='cislo_zapisu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='genetika_dna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='matka_manualni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='narozeni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='otec_manualni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_ed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_hd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_pater',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='srst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='typ_ochrany_klistata',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='vek',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='nazev',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='prispevky/'),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='plemeno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prispevky_na_zed', to='users.plemeno'),
        ),
    ]
