# Generated by Django 5.2.1 on 2026-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_pes_matka_remove_pes_otec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='qr_kod',
            field=models.ImageField(blank=True, null=True, upload_to='qr_kody/'),
        ),
    ]
