# Generated by Django 5.2.1 on 2026-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_pes_qr_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='plemeno',
            name='kategorie',
            field=models.CharField(choices=[('lovecka', 'Lovecká'), ('vystavy', 'Výstavy')], default='lovecka', max_length=50),
        ),
        migrations.AlterField(
            model_name='plemeno',
            name='slug',
            field=models.SlugField(default='docasny-slug', unique=True),
            preserve_default=False,
        ),
    ]
