# Generated by Django 5.2.1 on 2026-02-14 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_plemeno_kategorie_alter_plemeno_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerievideo',
            name='pes',
        ),
        migrations.AlterModelOptions(
            name='notifikace',
            options={},
        ),
        migrations.RenameField(
            model_name='ockovani',
            old_name='datum',
            new_name='datum_ockovani',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='barva',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='qr_kod',
        ),
        migrations.RemoveField(
            model_name='pes',
            name='srst',
        ),
        migrations.RemoveField(
            model_name='plemeno',
            name='kategorie',
        ),
        migrations.RemoveField(
            model_name='uspech',
            name='popis',
        ),
        migrations.AddField(
            model_name='ockovani',
            name='datum_pristi_navstevy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pes',
            name='chovna_stanice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pes',
            name='rodokmen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pes',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plemeno',
            name='ikona',
            field=models.ImageField(blank=True, upload_to='plemena_ikony/'),
        ),
        migrations.AlterField(
            model_name='notifikace',
            name='odesilatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifikace',
            name='prispevek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.prispevek'),
        ),
        migrations.AlterField(
            model_name='notifikace',
            name='typ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ockovani',
            name='nazev_vakciny',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pes',
            name='bonitace',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='cip',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='cislo_zapisu',
            field=models.CharField(blank=True, default='000', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='fotka',
            field=models.ImageField(blank=True, null=True, upload_to='profily_psu/'),
        ),
        migrations.AlterField(
            model_name='pes',
            name='matka_manualni',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Matka (jméno)'),
        ),
        migrations.AlterField(
            model_name='pes',
            name='otec_manualni',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otec (jméno)'),
        ),
        migrations.AlterField(
            model_name='pes',
            name='popis',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_ed',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_hd',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_pater',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='typ_ochrany_klistata',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='vek',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='libi_se_mi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prispevek',
            name='plemeno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prispevky_na_zed', to='users.plemeno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uspech',
            name='nazev',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uspech',
            name='typ',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zdravotnizaznam',
            name='pes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaznamy_zdravi', to='users.pes'),
        ),
        migrations.AlterField(
            model_name='zdravotnizaznam',
            name='titulek',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='galerie_psu/')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_fotky', to='users.pes')),
            ],
            options={
                'verbose_name': 'Fotka v galerii',
                'verbose_name_plural': 'Galerie fotek',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_soubor', models.FileField(upload_to='videa_psu/')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_videa', to='users.pes')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videa',
            },
        ),
        migrations.DeleteModel(
            name='GalerieFotka',
        ),
        migrations.DeleteModel(
            name='GalerieVideo',
        ),
    ]
