# Generated by Django 5.2.1 on 2026-02-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_galerievideo_pes_alter_notifikace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='qr_kod',
            field=models.ImageField(blank=True, null=True, upload_to='qr_kody/'),
        ),
    ]
