# Generated by Django 5.2.1 on 2026-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_pes_qr_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pes',
            name='bonitace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='chovna_stanice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='cislo_zapisu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rodokmen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_ed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pes',
            name='rtg_hd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
