# Generated by Django 5.2.1 on 2026-02-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_pes_bonitace_alter_pes_chovna_stanice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pes',
            name='vek',
        ),
        migrations.AddField(
            model_name='pes',
            name='datum_narozeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
    ]
