# Generated by Django 5.2.1 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_pes_vek_pes_datum_narozeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pes',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
