# Generated by Django 5.2.1 on 2026-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_pes_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmajitele',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
