# Generated by Django 5.2.1 on 2026-02-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profilmajitele_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pes',
            name='narozeni',
        ),
    ]
