# Generated by Django 5.2.1 on 2026-02-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_pes_narozeni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilmajitele',
            name='je_premium',
        ),
    ]
