# Generated by Django 5.2.1 on 2026-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktniZprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('predmet', models.CharField(max_length=200, verbose_name='Předmět')),
                ('zprava', models.TextField(verbose_name='Zpráva')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sluzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('obchod', 'Obchod pro psy'), ('veterina', 'Veterinář'), ('hotel', 'Psí hotel'), ('wellness', 'Wellness pro psy'), ('cvicak', 'Cvičiště'), ('utulek', 'Útulek')], max_length=20)),
                ('adresa', models.CharField(max_length=300)),
                ('popis', models.TextField(blank=True)),
                ('web', models.URLField(blank=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('lat', models.FloatField(verbose_name='Zeměpisná šířka')),
                ('lon', models.FloatField(verbose_name='Zeměpisná délka')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
