# Generated by Django 5.2.1 on 2026-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluzba',
            name='schvaleno',
            field=models.BooleanField(default=False, verbose_name='Schváleno administrátorem'),
        ),
    ]
