# Generated by Django 5.2.1 on 2026-02-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sluzba_schvaleno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sluzba',
            name='vlastnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moje_sluzby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sluzba',
            name='typ',
            field=models.CharField(choices=[('obchod', 'Obchod pro psy'), ('veterina', 'Veterinář'), ('hotel', 'Psí hotel'), ('wellness', 'Wellness pro psy'), ('cvicak', 'Cvičiště'), ('utulek', 'Útulek'), ('chovna_stanice', 'Chovná stanice')], max_length=20),
        ),
    ]
