# Generated by Django 5.2.1 on 2026-02-08 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sluzba_vlastnik_alter_sluzba_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spendlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('standard', 'Běžný bod'), ('nebezpeci', '⚠️ NEBEZPEČÍ')], default='standard', max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('text', models.TextField()),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('potvrzeni_minus', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
