# Generated by Django 5.2.1 on 2026-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_spendlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluzba',
            name='potvrzeni_minus',
            field=models.IntegerField(default=0, verbose_name='Nahlášení jako neaktuální'),
        ),
        migrations.AlterField(
            model_name='sluzba',
            name='typ',
            field=models.CharField(choices=[('nebezpeci', '⚠️ NEBEZPEČÍ (Návnady, střepy, apod.)'), ('obchod', 'Obchod pro psy'), ('veterina', 'Veterinář'), ('hotel', 'Psí hotel'), ('wellness', 'Wellness pro psy'), ('cvicak', 'Cvičiště'), ('utulek', 'Útulek'), ('chovna_stanice', 'Chovná stanice')], max_length=20),
        ),
    ]
