# Generated by Django 5.2.1 on 2026-02-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sluzba_potvrzeni_minus_alter_sluzba_typ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spendlik',
        ),
    ]
