# Generated by Django 5.2.1 on 2026-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_spendlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sluzba',
            name='typ',
            field=models.CharField(choices=[('nebezpeci', '⚠️ NEBEZPEČÍ (Návnady, střepy, apod.)'), ('obchod', 'Obchod pro psy'), ('veterina', 'Veterinář'), ('strihani', 'Stříhání psů / Salon'), ('hotel', 'Psí hotel'), ('wellness', 'Wellness pro psy'), ('cvicak', 'Cvičiště'), ('utulek', 'Útulek'), ('chovna_stanice', 'Chovná stanice')], max_length=20),
        ),
    ]
