# Generated by Django 5.2.1 on 2026-02-05 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inzerat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('stenata', 'Štěňata'), ('psi_feny', 'Dospělí psi a feny'), ('kryti', 'Krytí / Chov'), ('potreby', 'Potřeby a hračky'), ('krmivo', 'Krmivo'), ('oblecky', 'Oblečky'), ('ztraty', 'Ztráty a nálezy')], max_length=20, verbose_name='Kategorie')),
                ('titulek', models.CharField(max_length=200, verbose_name='Titulek inzerátu')),
                ('text', models.TextField(verbose_name='Popis')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena (Kč)')),
                ('mesto', models.CharField(max_length=100, verbose_name='Město / Lokalita')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='inzeraty/', verbose_name='Fotografie')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('aktivni', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inzerát',
                'verbose_name_plural': 'Inzeráty',
            },
        ),
    ]
