# Generated by Django 5.2.1 on 2026-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='inzeraty/videa/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='inzerat',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='inzeraty/obrazky/', verbose_name='Fotografie'),
        ),
    ]
