# Generated by Django 5.2.1 on 2026-02-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzerce', '0002_inzerat_video_alter_inzerat_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='inzeraty/obrazky/', verbose_name='Hlavní fotografie'),
        ),
        migrations.CreateModel(
            name='InzeratFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='inzeraty/galerie/', verbose_name='Další fotografie')),
                ('inzerat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='inzerce.inzerat')),
            ],
            options={
                'verbose_name': 'Fotografie z galerie',
                'verbose_name_plural': 'Fotografie z galerie',
            },
        ),
    ]
