# Generated by Django 5.2.1 on 2026-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzerce', '0003_alter_inzerat_obrazek_inzeratfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='kraj',
            field=models.CharField(choices=[('PHA', 'Praha'), ('STC', 'Středočeský'), ('JHC', 'Jihočeský'), ('PLK', 'Plzeňský'), ('KVK', 'Karlovarský'), ('ULK', 'Ústecký'), ('LBK', 'Liberecký'), ('HKK', 'Královéhradecký'), ('PAK', 'Pardubický'), ('VYS', 'Vysočina'), ('JMK', 'Jihomoravský'), ('OLK', 'Olomoucký'), ('ZLK', 'Zlínský'), ('MSK', 'Moravskoslezský')], default='PHA', max_length=3, verbose_name='Kraj'),
        ),
    ]
