# Generated by Django 5.2.1 on 2026-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzerce', '0004_inzerat_kraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='zobrazit_email',
            field=models.BooleanField(default=True, verbose_name='Zobrazit email v inzerátu'),
        ),
        migrations.AddField(
            model_name='inzerat',
            name='zobrazit_telefon',
            field=models.BooleanField(default=True, verbose_name='Zobrazit telefon v inzerátu'),
        ),
    ]
